#ifndef GN_CONN_STEP_E_H
#define GN_CONN_STEP_E_H

typedef enum
{
    GN_CONN_STEP_INVALID,
    GN_CONN_STEP_EXTR_MTHD,
    GN_CONN_STEP_EXTR_URI,
    GN_CONN_STEP_EXTR_PROT,
    GN_CONN_STEP_EXTR_HDRN,
    GN_CONN_STEP_EXTR_HDRV,
    GN_CONN_STEP_OPEN_LIST,
    GN_CONN_STEP_OPEN_FILE,
    GN_CONN_STEP_SEND_HDRS,
    GN_CONN_STEP_SEND_FILE,
    GN_CONN_STEP_RECV_DATA,
    GN_CONN_STEP_CLOSE
} gn_conn_step_e;

#endif // GN_CONN_STEP_E_H