#ifndef GN_CONN_MGMT_THRD_STATE_E_H
#define GN_CONN_MGMT_THRD_STATE_E_H

typedef enum
{
    GN_CONN_MGMT_THRD_STATE_STARTING,
    GN_CONN_MGMT_THRD_STATE_RUNNING,
    GN_CONN_MGMT_THRD_STATE_STOPPING,
    GN_CONN_MGMT_THRD_STATE_STOPPED
} gn_conn_mgmt_thrd_state_e;

#endif // GN_CONN_MGMT_THRD_STATE_E_H